// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nupcykupilllxkvgpkyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51cGN5a3VwaWxsbHhrdmdwa3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMTk3NjAsImV4cCI6MjA1Mjg5NTc2MH0.BsgTxO6Trd-A9_i2JoTuqpMMGSizoeo4agn1pPlzkZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);